Catch error for non-standard cursor
Adwaita icon theme does not contain `exchange` legacy X11 cursor
so attempting to mask HCY wheel on GNOME will cause a crash:

    Gdk-Message: Unable to load exchange from the cursor theme
    TypeError: constructor returned NULL

Let’s catch the error like in https://github.com/mypaint/mypaint/commit/cf14342d9ad609ffd92eef965450281f8ddb3fc1
and fall back to default cursor when not present.