setup.py: Ensure setuptools-compatible distutils are used
Setuptools is warning:

    lib/python3.9/site-packages/_distutils_hack/__init__.py:17: UserWarning: Distutils was imported before Setuptools, but importing Setuptools also replaces the `distutils` module in `sys.modules`. This may lead to undesirable behaviors or errors. To avoid these issues, avoid using distutils directly, ensure that setuptools is installed in the traditional way (e.g. not an editable install), and/or make sure that setuptools is always imported before distutils.

And in fact, I am getting such errors:

    distutils.errors.DistutilsClassError: command class <class '__main__.Build'> must subclass Command

Let’s do as asked.